name: ds_purchase
description: Purchase components for altush Flutter projects. Currently supports Adapty only
version: 2.1.3
homepage: https://github.com/al-tush/ds_purchase

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.0.0
  firebase_analytics: '>=10.10.0 <12.0.0'
  collection: ^1.16.0

  ds_common: ^2.1.1

  adapty_flutter: ^3.4.1

  in_app_purchase: ^3.2.0
  in_app_purchase_platform_interface: ^1.4.0
  in_app_purchase_android: ^0.3.6+12
  in_app_purchase_storekit: ^0.3.20+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.altush.ds_purchase
        pluginClass: DsPurchasePlugin
      ios:
        pluginClass: DsPurchasePlugin
